# Data gathered from: https://extapps.dec.ny.gov/docs/wildlife_pdf/2023dmps.pdf
library(tidyverse)
library(sf)
library(tmap)

DMPs_per_WMU = data.frame(DMPs = c(-999,
                                  175,
                                  2800,
                                  3600,
                                  5200,
                                  3600,
                                  5700,
                                  1200,
                                  45000,
                                  3500,
                                  1900,
                                  3000,
                                  -999,
                                  3000,
                                  3100,
                                  1900,
                                  13500,
                                  2800,
                                  2200,
                                  -999,
                                  3000,
                                  450,
                                  2100,
                                  2000,
                                  2000,
                                  1200,
                                  3900,
                                  400,
                                  2100,
                                  2400,
                                  2500,
                                  NA,
                                  NA,
                                  NA,
                                  NA,
                                  NA,
                                  NA,
                                  9700,
                                  1800,
                                  200,
                                  1700,
                                  4600,
                                  NA,
                                  22700,
                                  800,
                                  NA,
                                  8500,
                                  NA,
                                  8400,
                                  6100,
                                  5200,
                                  6800,
                                  27500,
                                  16000,
                                  38400,
                                  22000,
                                  2900,
                                  28800,
                                  12600,
                                  14500,
                                  -999,
                                  25500,
                                  28500,
                                  20000,
                                  17500,
                                  9800,
                                  20000,
                                  6000,
                                  16500,
                                  7700,
                                  6000,
                                  7000,
                                  13300,
                                  8500,
                                  20500,
                                  12200,
                                  9700,
                                  18300,
                                  16200,
                                  7000,
                                  6300,
                                  4900,
                                  4900,
                                  1800,
                                  900,
                                  1500,
                                  2150,
                                  1425,
                                  5100),
                          UNIT = c("1C",
                                  "3A",
                                  "3C",
                                  "3F",
                                  "3G",
                                  "3H",
                                  "3J",
                                  "3K",
                                  "3M",
                                  "3N",
                                  "3P",
                                  "3R",
                                  "3S",
                                  "4A",
                                  "4B",
                                  "4C",
                                  "4F",
                                  "4G",
                                  "4H",
                                  "4J",
                                  "4K",
                                  "4L",
                                  "4O",
                                  "4P",
                                  "4R",
                                  "4S",
                                  "4T",
                                  "4U",
                                  "4W",
                                  "4Y",
                                  "4Z",
                                  "5A",
                                  "5C",
                                  "5F",
                                  "5G",
                                  "5H",
                                  "5J",
                                  "5R",
                                  "5S",
                                  "5T",
                                  "6A",
                                  "6C",
                                  "6F",
                                  "6G",
                                  "6H",
                                  "6J",
                                  "6K",
                                  "6N",
                                  "6P",
                                  "6R",
                                  "6S",
                                  "7A",
                                  "7F",
                                  "7H",
                                  "7J",
                                  "7M",
                                  "7P",
                                  "7R",
                                  "7S",
                                  "8A",
                                  "8C",
                                  "8F",
                                  "8G",
                                  "8H",
                                  "8J",
                                  "8M",
                                  "8N",
                                  "8P",
                                  "8R",
                                  "8S",
                                  "8T",
                                  "8W",
                                  "8X",
                                  "8Y",
                                  "9A",
                                  "9F",
                                  "9G",
                                  "9H",
                                  "9J",
                                  "9K",
                                  "9M",
                                  "9N",
                                  "9P",
                                  "9R",
                                  "9S",
                                  "9T",
                                  "9W",
                                  "9X",
                                  "9Y"))

WMUs = read_sf(paste0(getwd(),"/Data/Input_data/Wildlife_Management_Units_5181502506492967745/Wildlife_Management_Units.shp")) %>%
  st_transform(.,32618)

DMP_spatial = left_join(DMPs_per_WMU,WMUs) %>%
  st_set_geometry(.,'geometry')

pal = viridisLite::viridis(n=5,end = .7)

DMP_map=tm_shape(DMP_spatial %>%
             filter(DMPs != -999),
           bbox = st_bbox(WMUs))+tm_polygons(col='DMPs',
                                             legend.show=F,
                                             palette=viridisLite::viridis(n=5,end = .7)) +
tm_shape(DMP_spatial %>%
           filter(DMPs == -999))+tm_polygons(col='#FDE725FF')+
tm_shape(DMP_spatial %>%
           filter(is.na(DMPs)==T))+tm_polygons(col='grey50')+
  tm_layout(legend.position=c('left','top'))+
tm_add_legend(type='fill',
              title = "Deer Management Permits",
              col = c(pal[1],
                      pal[2],
                      pal[3],
                      pal[4],
                      pal[5],
                      "#FDE725FF",
                      "grey50"),
              labels = c("0 to 10,000",
                         "10,000 to 20,000",
                         "20,000 to 30,000",
                         "30,000 to 40,000",
                         "40,000 to 50,000",
                         "Maximize",
                         "Missing"));DMP_map
tmap_save(DMP_map,
          filename = paste0(getwd(),"/Figures/Deer_Management_Permits.jpeg"),
          dpi=300)
